#:import MapView kivy_garden.mapview.MapView

MainLayout:

<MainLayout>:
    BoxLayout:
        orientation:'vertical'

        MapView:
            id: map
            size_hint_y: 0.65
        
        ScrollView:
            size_hint_y: 0.35

            MDLabel:
                id: info
                text: ""
                size_hint_y: None
                height: self.texture_size[1]
                text_size: self.width, None
                hailign: "left"
                valign: "top"